-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

local wezterm = require 'wezterm';

local wezterm = require 'wezterm'

return {

  -- Set window background opacity to 95%
  window_background_opacity = 0.95,

  -- Define a custom color scheme based on Afterglow
  color_schemes = {
    ["AfterglowCustom"] = {
      foreground = "#d0d0d0",
      background = "#0c0c0c",
      cursor_bg = "#d0d0d0",
      cursor_border = "#d0d0d0",
      cursor_fg = "#1c1e26",
      selection_bg = "#3e4451",
      selection_fg = "#d0d0d0",
      ansi = {
        "#151515",  -- Black
        "#ac4142",  -- Red
        "#90a959",  -- Green
        "#f4bf75",  -- Yellow
        "#6a9fb5",  -- Blue
        "#aa759f",  -- Magenta
        "#75b5aa",  -- Cyan
        "#d0d0d0",  -- White
      },
      brights = {
        "#505354",  -- Bright Black
        "#ac4142",  -- Bright Red
        "#90a959",  -- Bright Green
        "#f4bf75",  -- Bright Yellow
        "#6a9fb5",  -- Bright Blue
        "#aa759f",  -- Bright Magenta
        "#75b5aa",  -- Bright Cyan
        "#f5f5f5",  -- Bright White
      },
    },
  },

  -- Apply the custom color scheme
  color_scheme = "AfterglowCustom",
  
  -- Other WezTerm settings
  -- font_size = 12.0,
  -- font = wezterm.font("JetBrains Mono"),
  -- font = wezterm.font("NotoMono Nerd Font"),
  -- font = wezterm.font("0xProto Nerd Font Mono"),
  font = wezterm.font("FiraCode"),
  initial_cols = 110,
  initial_rows = 25,
}


