// Icon and condition tables adapted from Meteobar 0.5.4 (MIT, mryll).
// See ../LICENSE and ../UPSTREAM. No executable dependency.
var conditions = {
  "0": {
    "day_nerd": "󰖙",
    "night_nerd": "󰖔",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "☀️",
    "night_emoji": "🌙",
    "day_fa": "",
    "night_fa": "",
    "css_class": "clear",
    "description": "Clear sky"
  },
  "1": {
    "day_nerd": "󰖙",
    "night_nerd": "󰖔",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌤️",
    "night_emoji": "🌙",
    "day_fa": "",
    "night_fa": "",
    "css_class": "clear",
    "description": "Mainly clear"
  },
  "2": {
    "day_nerd": "󰖕",
    "night_nerd": "󰼱",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "⛅",
    "night_emoji": "☁️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "cloudy",
    "description": "Partly cloudy"
  },
  "3": {
    "day_nerd": "󰖐",
    "night_nerd": "󰖐",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "☁️",
    "night_emoji": "☁️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "cloudy",
    "description": "Overcast"
  },
  "45": {
    "day_nerd": "󰖑",
    "night_nerd": "󰖑",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌫️",
    "night_emoji": "🌫️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "foggy",
    "description": "Fog"
  },
  "48": {
    "day_nerd": "󰖑",
    "night_nerd": "󰖑",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌫️",
    "night_emoji": "🌫️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "foggy",
    "description": "Rime fog"
  },
  "51": {
    "day_nerd": "󰖗",
    "night_nerd": "󰖗",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌦️",
    "night_emoji": "🌧️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "rainy",
    "description": "Light drizzle"
  },
  "53": {
    "day_nerd": "󰖗",
    "night_nerd": "󰖗",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌧️",
    "night_emoji": "🌧️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "rainy",
    "description": "Moderate drizzle"
  },
  "55": {
    "day_nerd": "󰖗",
    "night_nerd": "󰖗",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌧️",
    "night_emoji": "🌧️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "rainy",
    "description": "Dense drizzle"
  },
  "56": {
    "day_nerd": "󰖗",
    "night_nerd": "󰖗",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌧️",
    "night_emoji": "🌧️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "rainy",
    "description": "Freezing drizzle"
  },
  "57": {
    "day_nerd": "󰖗",
    "night_nerd": "󰖗",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌧️",
    "night_emoji": "🌧️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "rainy",
    "description": "Dense freezing drizzle"
  },
  "61": {
    "day_nerd": "󰖗",
    "night_nerd": "󰖗",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌧️",
    "night_emoji": "🌧️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "rainy",
    "description": "Slight rain"
  },
  "63": {
    "day_nerd": "󰖗",
    "night_nerd": "󰖗",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌧️",
    "night_emoji": "🌧️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "rainy",
    "description": "Moderate rain"
  },
  "65": {
    "day_nerd": "󰖗",
    "night_nerd": "󰖗",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌧️",
    "night_emoji": "🌧️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "rainy",
    "description": "Heavy rain"
  },
  "66": {
    "day_nerd": "󰖗",
    "night_nerd": "󰖗",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌧️",
    "night_emoji": "🌧️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "rainy",
    "description": "Freezing rain"
  },
  "67": {
    "day_nerd": "󰖗",
    "night_nerd": "󰖗",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌧️",
    "night_emoji": "🌧️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "rainy",
    "description": "Heavy freezing rain"
  },
  "71": {
    "day_nerd": "󰖘",
    "night_nerd": "󰖘",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌨️",
    "night_emoji": "🌨️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "snowy",
    "description": "Slight snow"
  },
  "73": {
    "day_nerd": "󰖘",
    "night_nerd": "󰖘",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌨️",
    "night_emoji": "🌨️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "snowy",
    "description": "Moderate snow"
  },
  "75": {
    "day_nerd": "󰖘",
    "night_nerd": "󰖘",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌨️",
    "night_emoji": "🌨️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "snowy",
    "description": "Heavy snow"
  },
  "77": {
    "day_nerd": "󰖘",
    "night_nerd": "󰖘",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌨️",
    "night_emoji": "🌨️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "snowy",
    "description": "Snow grains"
  },
  "80": {
    "day_nerd": "󰖗",
    "night_nerd": "󰖗",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌧️",
    "night_emoji": "🌧️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "rainy",
    "description": "Slight rain showers"
  },
  "81": {
    "day_nerd": "󰖗",
    "night_nerd": "󰖗",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌧️",
    "night_emoji": "🌧️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "rainy",
    "description": "Moderate rain showers"
  },
  "82": {
    "day_nerd": "󰖗",
    "night_nerd": "󰖗",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌧️",
    "night_emoji": "🌧️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "rainy",
    "description": "Violent rain showers"
  },
  "85": {
    "day_nerd": "󰖘",
    "night_nerd": "󰖘",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌨️",
    "night_emoji": "🌨️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "snowy",
    "description": "Slight snow showers"
  },
  "86": {
    "day_nerd": "󰖘",
    "night_nerd": "󰖘",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "🌨️",
    "night_emoji": "🌨️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "snowy",
    "description": "Heavy snow showers"
  },
  "95": {
    "day_nerd": "󰖓",
    "night_nerd": "󰖓",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "⛈️",
    "night_emoji": "⛈️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "stormy",
    "description": "Thunderstorm"
  },
  "96": {
    "day_nerd": "󰖓",
    "night_nerd": "󰖓",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "⛈️",
    "night_emoji": "⛈️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "stormy",
    "description": "Thunderstorm with hail"
  },
  "99": {
    "day_nerd": "󰖓",
    "night_nerd": "󰖓",
    "day_weather": "",
    "night_weather": "",
    "day_emoji": "⛈️",
    "night_emoji": "⛈️",
    "day_fa": "",
    "night_fa": "",
    "css_class": "stormy",
    "description": "Thunderstorm with heavy hail"
  }
};
var german = {
  "Clear sky": "Klarer Himmel",
  "Mainly clear": "Überwiegend klar",
  "Partly cloudy": "Teilweise bewölkt",
  "Overcast": "Bedeckt",
  "Fog": "Nebel",
  "Rime fog": "Raureifnebel",
  "Light drizzle": "Leichter Nieselregen",
  "Moderate drizzle": "Mäßiger Nieselregen",
  "Dense drizzle": "Starker Nieselregen",
  "Freezing drizzle": "Gefrierender Nieselregen",
  "Dense freezing drizzle": "Starker gefrierender Nieselregen",
  "Slight rain": "Leichter Regen",
  "Moderate rain": "Mäßiger Regen",
  "Heavy rain": "Starker Regen",
  "Freezing rain": "Gefrierender Regen",
  "Heavy freezing rain": "Starker gefrierender Regen",
  "Slight snow": "Leichter Schneefall",
  "Moderate snow": "Mäßiger Schneefall",
  "Heavy snow": "Starker Schneefall",
  "Snow grains": "Schneegriesel",
  "Slight rain showers": "Leichte Regenschauer",
  "Moderate rain showers": "Mäßige Regenschauer",
  "Violent rain showers": "Heftige Regenschauer",
  "Slight snow showers": "Leichte Schneeschauer",
  "Heavy snow showers": "Starke Schneeschauer",
  "Thunderstorm": "Gewitter",
  "Thunderstorm with hail": "Gewitter mit Hagel",
  "Thunderstorm with heavy hail": "Gewitter mit starkem Hagel"
};
function condition(code, day, iconSet, language) {
  var entry = conditions[String(code)] || conditions["0"];
  var family = iconSet === "fontawesome" ? "fa" : iconSet;
  return { icon: entry[(day ? "day_" : "night_") + family] || entry.day_nerd,
    description: language === "de" ? (german[entry.description] || entry.description) : entry.description,
    condition: entry.css_class };
}
if (typeof module !== "undefined") module.exports = { condition: condition, conditions: conditions };
